#ifndef CTC_SIGMA_PARAMETERS_H
#define CTC_SIGMA_PARAMETERS_H

#include <stddef.h>
#include <stdint.h>

#define CTC_SIGMA_VERSION_STRING "0.2.0-dev"

#define CTC_FIELD_MODULUS UINT64_C(2305843009213693951)
#define CTC_BRAID_STRANDS 8U
#define CTC_STATE_LANES 16U
#define CTC_BRANCH_LANES 8U
#define CTC_FEISTEL_ROUNDS 12U
#define CTC_FACTORS_PER_BRANCH 32U
#define CTC_GARSIDE_KEEP_WINDOW 16U
#define CTC_RATE_BYTES 40U
#define CTC_RATE_LANES 8U
#define CTC_HASH256_BYTES 32U
#define CTC_SIMPLE_FACTOR_COUNT 40320U
#define CTC_NON_IDENTITY_FACTOR_COUNT 40319U

#define CTC_ARITH_PRE_SUBROUNDS 4U
#define CTC_ARITH_ENCODER_SUBROUNDS 4U
#define CTC_ARITH_FOLD_GROUP_SUBROUNDS 2U
#define CTC_ARITH_FOLD_FINAL_SUBROUNDS 6U
#define CTC_ARITH_POST_SUBROUNDS 6U

#define CTC_MAX_NORMAL_FACTORS 512U
#define CTC_MAX_FOLD_TOKENS (CTC_MAX_NORMAL_FACTORS + 8U)
#define CTC_ENCODER_MAX_BLOCKS 1048576U
#define CTC_SQUEEZE_MAX_REJECTIONS 1048576U

#endif
